### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by ghost** [BlossomiShymae/clean-cuts#1]
You know LoL is played in different regions and so there are translations of LoL for those languages, is it possible to add those translations to the site? especially for items.

**Comment by BlossomiShymae** [comment]
I meant to add support for this but forgot. Maybe soon. x3

**Comment by ghost** [comment]
That would be really great, thank you very much.

**Comment by ghost** [comment]
@BlossomiShymae I would like to host it for myself, can we use other languages only?

**Comment by BlossomiShymae** [comment]
Added support for other languages. This only applies to game data.
